import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import 'package:printing/printing.dart';

void main() {
  runApp(const EcoTourApp());
}

class EcoTourApp extends StatelessWidget {
  const EcoTourApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'EcoTour PDF Generator',
      home: PdfHomePage(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class PdfHomePage extends StatelessWidget {
  PdfHomePage({super.key});

  final List<Map<String, dynamic>> communityProjects = [
    {
      "name": "Water Conservation Initiative",
      "location": "Nakuru",
      "status": "Active",
      "beneficiaries": 120,
    },
    {
      "name": "EcoTour Training Program",
      "location": "Naivasha",
      "status": "Completed",
      "beneficiaries": 45,
    },
    {
      "name": "Youth Skills Empowerment",
      "location": "Nairobi",
      "status": "Active",
      "beneficiaries": 200,
    },
  ];

  final List<Map<String, dynamic>> touristClients = [
    {
      "name": "Maeve Jones",
      "nationality": "Canadian",
      "booking": "Airport Transfer",
      "date": "2025-03-12",
    },
    {
      "name": "Maria Gonzales",
      "nationality": "Spain",
      "booking": "Game Drive",
      "date": "2025-03-10",
    },
    {
      "name": "Esther Wanjiku",
      "nationality":"Kenyan",
      "booking": "Hotel Check-In",
      "date": "2025-03-11",
    },
  ];

  Future<Uint8List> generatePdf() async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(25),
        build: (pw.Context context) {
          return [
            pw.Header(
              child: pw.Text(
                "EcoTour Assist – Report Summary",
                style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
              ),
            ),

            pw.Text("Generated by: Matthew Nyamu"),
            pw.SizedBox(height: 20),

            pw.Text(
              "📌 Community Development Projects",
              style:
                  pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 10),

            pw.Table.fromTextArray(
              headers: ["Project", "Location", "Status", "Beneficiaries"],
              data: communityProjects.map(
                (p) => [
                  p["name"],
                  p["location"],
                  p["status"],
                  p["beneficiaries"].toString()
                ],
              ).toList(),
            ),

            pw.SizedBox(height: 20),

            pw.Text(
              "🧳 Tourist Bookings",
              style:
                  pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 10),

            pw.Table.fromTextArray(
              headers: ["Name", "Nationality", "Booking", "Date"],
              data: touristClients.map(
                (c) => [
                  c["name"],
                  c["nationality"],
                  c["booking"],
                  c["date"]
                ],
              ).toList(),
            ),

            pw.SizedBox(height: 20),

            pw.Text(
              "Total Beneficiaries: ${communityProjects.fold(0, (sum, p) => sum + p['beneficiaries'])}",
              style: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.green,
                fontSize: 16,
              ),
            ),

            pw.SizedBox(height: 20),

            pw.Paragraph(
              text:
                  "This PDF report highlights both community development initiatives and tourism service bookings under the EcoTour Assist program. It showcases administrative, reporting, tourism management, and data organization skills.",
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("PDF Generator"),
        backgroundColor: Colors.green,
      ),
      body: Center(
        child: ElevatedButton.icon(
          icon: const Icon(Icons.picture_as_pdf),
          label: const Text("Generate PDF"),
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.green,
            padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 15),
            textStyle: const TextStyle(fontSize: 18),
          ),
          onPressed: () async {
            final pdfData = await generatePdf();

            // Opens viewer + gives download option
            await Printing.layoutPdf(onLayout: (format) async => pdfData);
          },
        ),
      ),
    );
  }
}
